/** @type {import("tailwindcss").Config} */
module.exports = {
  content: ["./web/templates/**/*.html", "./web/static/js/*.js"],
  safelist: [
    "cais-password-wrap",
    "cais-password-toggle",
    "cais-chat-scroll-down",
    "cais-thinking",
    "cais-thinking-dots",
    "cais-select-search",
    "cais-select-search-native",
    "cais-select-search-trigger",
    "cais-select-search-panel",
    "cais-select-search-input",
    "cais-select-search-list",
    "cais-select-search-option",
    "cais-select-search-label",
    "cais-select-search-chevron",
    "is-selected",
    "is-highlighted",
    "is-hidden",
  ],
  theme: {
    extend: {
      colors: {
        // CloudStore M3 token palette (from the Stitch design export).
        "on-error": "#690005",
        "tertiary-container": "#ca8100",
        "on-surface-variant": "#c2c6d6",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#3e2400",
        "surface-tint": "#adc6ff",
        "on-primary-container": "#00285d",
        "on-primary": "#002e6a",
        "surface-variant": "#26364a",
        error: "#ffb4ab",
        "inverse-primary": "#005ac2",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-low": "#0b1c30",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary": "#003824",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed": "#ffddb8",
        outline: "#8c909f",
        "secondary-fixed": "#6ffbbe",
        "primary-container": "#4d8eff",
        "inverse-on-surface": "#213145",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#93000a",
        tertiary: "#ffb95f",
        "on-secondary-container": "#00311f",
        "surface-container-lowest": "#000f21",
        "surface-container-high": "#1b2b3f",
        background: "#031427",
        "on-background": "#d3e4fe",
        surface: "#031427",
        "secondary-fixed-dim": "#4edea3",
        primary: "#adc6ff",
        secondary: "#4edea3",
        "inverse-surface": "#d3e4fe",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#004395",
        "surface-bright": "#2a3a4f",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#26364a",
        "primary-fixed": "#d8e2ff",
        "surface-dim": "#031427",
        "surface-container": "#102034",
        "outline-variant": "#424754",
        "on-surface": "#d3e4fe",
        "secondary-container": "#00a572",
        "on-tertiary": "#472a00",
        // Scaffold kit aliases kept so shipped components keep working; repointed
        // to the CloudStore palette so the console reads blue instead of copper.
        ink: "#031427",
        foam: "#d3e4fe",
        copper: "#4d8eff",
        tide: "#102034",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "1.75rem",
        margin: "1.25rem",
      },
      fontFamily: {
        sans: ["Geist", "Avenir Next", "Segoe UI", "Helvetica Neue", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "headline-xl": ["Geist", "system-ui", "sans-serif"],
        "headline-lg": ["Geist", "system-ui", "sans-serif"],
        "headline-md": ["Geist", "system-ui", "sans-serif"],
        "headline-sm": ["Geist", "system-ui", "sans-serif"],
        "body-lg": ["Geist", "system-ui", "sans-serif"],
        "body-md": ["Geist", "system-ui", "sans-serif"],
        "body-sm": ["Geist", "system-ui", "sans-serif"],
        "label-md": ["Geist", "system-ui", "sans-serif"],
        "label-sm": ["Geist", "system-ui", "sans-serif"],
        "code-md": ['"JetBrains Mono"', "ui-monospace", "monospace"],
        "code-sm": ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "headline-xl": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg": [
          "22px",
          { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "headline-md": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": [
          "15px",
          { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "code-md": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "code-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      boxShadow: {
        "2xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
    },
  },
  plugins: [],
};
